apps:
  - name: adminserver
    port: 60004
  - name: webserver
    port: 8090
  - name: apiserver
    port: 8080
  - name: coreservice
    port: 50009
  - name: toposerver
    port: 60002
  - name: hostserver
    port: 60001


image:
  repository: harbor.dev.21vianet.com/cmdb/
  tag: "2022322_12283"

env:

  pullPolicy: IfNotPresent

#res:
#  req:
#    mem: 1024Mi
#    cpu: 600m
#  req2:
#    mem: 2048Mi
#  req3:
#    mem: 3072Mi
#  ave:
#    mem: 1024Mi
#    cpu: 1000m
